listNum = ["abc", "efg", "hij", [1, 2, 3]]
listNum1 = ["stu"]
listNum2 = list(range(5))
print(listNum)
print(listNum[0:2])
print(listNum.pop(1))
listNum.append("lmn")
print(listNum)
listNum.remove([1, 2, 3])
print(listNum)
listNum.insert(0,"opq")
print(listNum)
listNum.reverse()
print(listNum)
print(len(listNum))
print(max(listNum))
listNum1.extend(listNum2)
print(listNum1)
listNum3 = listNum.copy()
print(listNum3)